pool:
    vmImage: 'ubuntu-latest'
variables:
    BUILD_NUMBER: $[counter('buildCounter',1)]
    NUGET_REPO_URL: https://api.nuget.org/v3/index.json
    
trigger:
    branches:
        include:
        - master
        - refs/tags/*

pr:
    branches:
        include:
        - master

steps:
    - task: UseDotNet@2
      inputs:
        version: '8.0.100'

    - task: DotNetCoreCLI@2
      displayName: "Restore tools"
      inputs:
        command: custom
        custom: tool
        arguments: restore

    - task: AzureCLI@2
      env:
        NUGET_REPO_KEY: $(NUGET_REPO_KEY)
      inputs:
        azureSubscription: 'OSS Testing'
        scriptType: 'bash'
        addSpnToEnvironment: true
        scriptLocation: 'inlineScript'
        ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags') }}:
          inlineScript: 'dotnet fsi build.fsx -t release'
        ${{ if not(startsWith(variables['Build.SourceBranch'], 'refs/tags')) }}:
          inlineScript: 'dotnet fsi build.fsx -t ci'
            